name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Generate cache key
        run: .github/scripts/checksum.sh checksum.txt

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Test Plugin
        run: ./gradlew check :kmp4free:apiCheck --stacktrace --scan

      - name: (Fail-only) Bundle test reports
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

      - name: (Fail-only) Upload the build report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: error-report
          path: build-reports.zip

  perf-control:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Performance Tests - Warm Up
        run: ./gradlew check --rerun-tasks --stacktrace --scan

      - name: Performance Tests - jvm
        run: ./gradlew :samples:jvm:assemble -Pperftest=:samples:jvm --rerun-tasks --stacktrace --scan

      - name: Performance Tests - multiplatform
        run: ./gradlew :samples:multiplatform:assemble -Pperftest=:samples:multiplatform --rerun-tasks --stacktrace --scan

  perf-kmp4free-disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Performance Tests - Warm Up
        run: ./gradlew check -Pkmp4free=false -Pios=false -Pjs=false--rerun-tasks --stacktrace --scan

      - name: Performance Tests - jvm kmp4free disabled
        run: ./gradlew :samples:jvm_kmp4free:assemble -Pkmp4free=false -Pios=false -Pjs=false -Pperftest=:samples:jvm_kmp4free --rerun-tasks --stacktrace --scan

      - name: Performance Tests - multiplatform kmp4free disabled
        run: ./gradlew :samples:multiplatform_kmp4free:assemble -Pkmp4free=false -Pios=false -Pjs=false -Pperftest=:samples:multiplatform_kmp4free --stacktrace --scan

  perf-kmp4free-enabled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Performance Tests - Warm Up
        run: ./gradlew check -Pkmp4free=true -Pios=false -Pjs=false--rerun-tasks --stacktrace --scan

      - name: Performance Tests - jvm kmp4free enabled
        run: ./gradlew :samples:jvm_kmp4free:assemble -Pkmp4free=true -Pios=false -Pjs=false -Pperftest=:samples:jvm_kmp4free --rerun-tasks --stacktrace --scan

      - name: Performance Tests - multiplatform kmp4free enabled
        run: ./gradlew :samples:multiplatform_kmp4free:assemble -Pkmp4free=true -Pios=false -Pjs=false -Pperftest=:samples:multiplatform_kmp4free --rerun-tasks --stacktrace --scan


  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'handstandsam/kmp4free' && github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Upload Snapshot
        run: ./gradlew -p kmp4free clean publish --no-daemon --no-parallel --no-configuration-cache --stacktrace
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

      - name: Retrieve Version
        run: echo "VERSION_NAME=$(./gradlew -q -p kmp4free printVersionName)" >> $GITHUB_ENV

      - name: Publish release (main only)
        run: ./gradlew -p kmp4free closeAndReleaseRepository --no-daemon --no-parallel
        if: success() && !endsWith(env.VERSION_NAME, '-SNAPSHOT')
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
